### PR TITLE
Add wiener denoise unit test

### PR DESCRIPTION
**Pull request by edmond-zhu**
1. Add wiener denoise unit test
2. Add environment setup for unit test.

### CODE REVIEW

**Comment by edmond-zhu** [comment]
# For wiener denoise 2d unit test

# Pr for add wiener denoise 2d unit test
## license: check if license is ok
## Comments
## warnings in Local build
1. mac: no new warning, only warning: -pie being ignored. It is only used when linking a main executable
2. linux: GNU warning in SpatialFullDistortionTest.cc
3. windows: none

## warnings on remote ci servers
1. jenkins:
a. clang-format
b. 
2. travis
  a. mac: `-pie being ignored. It is only used when linking a main executable`, can be ignored.
  b. linux: SpaticalFullDistoration wanring, could be fixed by merge the latest code;
3. appvedor
  a. no warnings

## dry run output
~~~
Running main() from C:\Works\AV1\SVT-AV1\third_party\googletest\src\gtest_main.cc
Note: Google Test filter = Denoise/*.*
[==========] Running 36 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 9 tests from Denoise/WienerDenoiseLbdTest
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/0
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/0 (111 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/1
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/1 (70 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/2
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/2 (111 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/0
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/0 (108 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/1
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/1 (69 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/2
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/2 (108 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_gradient_test/0
[       OK ] Denoise/WienerDenoiseLbdTest.run_gradient_test/0 (287 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_gradient_test/1
[       OK ] Denoise/WienerDenoiseLbdTest.run_gradient_test/1 (122 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_gradient_test/2
[       OK ] Denoise/WienerDenoiseLbdTest.run_gradient_test/2 (289 ms)
[----------] 9 tests from Denoise/WienerDenoiseLbdTest (1284 ms total)

[----------] 27 tests from Denoise/WienerDenoiseHbdTest
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/0
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/0 (113 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/1
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/1 (68 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/2
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/2 (111 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/3
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/3 (112 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/4
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/4 (69 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/5
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/5 (121 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/6
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/6 (111 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/7
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/7 (68 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/8
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/8 (111 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/0
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/0 (109 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/1
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/1 (67 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/2
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/2 (108 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/3
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/3 (108 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/4
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/4 (66 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/5
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/5 (109 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/6
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/6 (111 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/7
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/7 (71 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/8
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/8 (108 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/0
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/0 (289 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/1
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/1 (122 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/2
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/2 (290 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/3
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/3 (288 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/4
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/4 (122 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/5
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/5 (287 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/6
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/6 (295 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/7
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/7 (122 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/8
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/8 (286 ms)
[----------] 27 tests from Denoise/WienerDenoiseHbdTest (3883 ms total)

[----------] Global test environment tear-down
[==========] 36 tests from 2 test cases ran. (5178 ms total)
[  PASSED  ] 36 tests.
~~~

**Comment by edmond-zhu** [comment]
@FochQu please verify it with following command:
SvtAv1UnitTests --gtest_filter=Denoise/*.*

**Comment by FochQu** [comment]
Branch for add_denoise_test
-----
+MAC:
ld: warning: -pie being ignored. It is only used when linking a main executable

+Linux
no warning

+Windows
no warning

Dry run test
--
Running main() from /home/jenkins/workspace/NightlyCidana-SVT-AV1/third_party/googletest/src/gtest_main.cc
Note: Google Test filter = Denoise/*.*
[==========] Running 36 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 9 tests from Denoise/WienerDenoiseLbdTest
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/0
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/0 (23 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/1
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/1 (22 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/2
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_block_size/2 (19 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/0
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/0 (19 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/1
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/1 (17 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/2
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseLbdTest.run_invalid_chroma_subsampling/2 (19 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_gradient_test/0
[       OK ] Denoise/WienerDenoiseLbdTest.run_gradient_test/0 (35 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_gradient_test/1
[       OK ] Denoise/WienerDenoiseLbdTest.run_gradient_test/1 (29 ms)
[ RUN      ] Denoise/WienerDenoiseLbdTest.run_gradient_test/2
[       OK ] Denoise/WienerDenoiseLbdTest.run_gradient_test/2 (34 ms)
[----------] 9 tests from Denoise/WienerDenoiseLbdTest (217 ms total)

[----------] 27 tests from Denoise/WienerDenoiseHbdTest
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/0
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/0 (19 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/1
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/1 (18 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/2
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/2 (19 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/3
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/3 (20 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/4
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/4 (18 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/5
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/5 (19 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/6
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/6 (19 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/7
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/7 (17 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/8
Unsupported block size 18
Unsupported block size 9
Unsupported block size 48
Unsupported block size 24
Unsupported block size 64
[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_block_size/8 (19 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/0
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/0 (18 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/1
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/1 (17 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/2
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/2 (19 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/3
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/3 (19 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/4
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/4 (17 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/5
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/5 (18 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/6
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/6 (19 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/7
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/7 (17 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/8
aom_wiener_denoise_2d doesn't handle different chroma subsamplingaom_wiener_denoise_2d doesn't handle different chroma subsampling[       OK ] Denoise/WienerDenoiseHbdTest.run_invalid_chroma_subsampling/8 (18 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/0
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/0 (35 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/1
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/1 (29 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/2
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/2 (35 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/3
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/3 (34 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/4
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/4 (29 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/5
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/5 (35 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/6
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/6 (34 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/7
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/7 (29 ms)
[ RUN      ] Denoise/WienerDenoiseHbdTest.run_gradient_test/8
[       OK ] Denoise/WienerDenoiseHbdTest.run_gradient_test/8 (35 ms)
[----------] 27 tests from Denoise/WienerDenoiseHbdTest (625 ms total)

[----------] Global test environment tear-down
[==========] 36 tests from 2 test cases ran. (843 ms total)
[  PASSED  ] 36 tests.

**Comment by Cidana-Developers** [comment]
No need to merge it for now.

**Pull request closed without merging**
