### PR TITLE
Add unit tests of compute mean

### PR DESCRIPTION
**Pull request by edmond-zhu**
Add unit tests of compute mean

### CODE REVIEW

**Review by Cidana-Developers — COMMENTED** [review]
The test data is generated randomly, we should add test patterns to test extreme value or saturated values?

**Comment by FochQu** [comment]
test email

**Review by Cidana-Developers — APPROVED** [review]

**Comment by Cidana-Developers** [comment]
I will merge it manually.

**Comment by Cidana-Developers** [comment]
merged, close it.

**Pull request merged**
