### PR TITLE
Add filter intra predictor unit test

### PR DESCRIPTION
**Pull request by edmond-zhu**
1. Add unit test of filter intra predictor:
 - eb_av1_filter_intra_predictor_sse4_1

### CODE REVIEW

**Comment by edmond-zhu** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*/FilterIntraPredTest.*

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 11%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPacketizationProcess.c.o<br />
[ 11%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPacketizationReorderQueue.c.o<br />
[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureAnalysisProcess.c.o<br />
[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureAnalysisResults.c.o<br />
[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureBufferDesc.c.o<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureControlSet.c.o<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionProcess.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbPictureDecisionProcess.c: In function ‘picture_decision_kernel’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbPictureDecisionProcess.c:3657:84: warning: array subscript is above array bounds [-Warray-bounds]<br />
                                         picture_control_set_ptr-&gt;temp_filt_pcs_list[pic_i + num_past_pics + 1] = pcs_itr;<br />
                                                                                    ^<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionQueue.c.o<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionReorderQueue.c.o<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionResults.c.o<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDemuxResults.c.o<br />
[ 15%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureManagerQueue.c.o<br />
[ 15%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureManagerReorderQueue.c.o<br />
–<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/FwdTxfm2dTest.cc.o<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/HbdVarianceTest.cc.o<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/IntraBcUtilTest.cc.o<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm1dTest.cc.o<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm2dAsmTest.cc.o<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InversetransformTests.cc.o<br />
[ 82%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/MotionEstimationTest.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/MotionEstimationTest.cc:12:0:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbMeSadCalculation.h:143:35: warning: ‘initialize_buffer32bits_func_ptr_array’ defined but not used [-Wunused-variable]<br />
     static EbInializeBuffer32Bits initialize_buffer32bits_func_ptr_array[ASM_TYPE_TOTAL] = {<br />
                                   ^<br />
[ 82%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/NoiseExtractTest.cc.o<br />
[ 82%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PackUnPackTest.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PictureAdditionTest.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PictureOperatorTest.cc.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc: In constructor ‘{anonymous}::PictureOperatorTest::PictureOperatorTest()’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc:215:25: warning: ‘{anonymous}::PictureOperatorTest::pu_height_’ will be initialized after [-Wreorder]<br />
     uint32<em>t pu_width</em>, pu_height_;<br />
                         ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc:214:17: warning:   ‘{anonymous}::TestPattern {anonymous}::PictureOperatorTest::test_pattern_’ [-Wreorder]<br />
     TestPattern test_pattern_;<br />
                 ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc:84:5: warning:   when initialized here [-Wreorder]<br />
     PictureOperatorTest()<br />
     ^<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PsnrTest.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/QuantAsmTest.cc.o<br />
[ 84%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/ResidualTest.cc.o<br />
[ 84%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/RestorationPickTest.cc.o<br />
[ 84%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SadTest.cc.o<br />
[ 85%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SelfGuidedUtilTest.cc.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>/FilterIntraPredTest.</em><br />
[==========] Running 70 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 70 tests from AV1/FilterIntraPredTest<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/0<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/0 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/1<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/1 (6 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/2<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/2 (10 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/3<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/3 (20 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/4<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/4 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/5<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/5 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/6<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/6 (7 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/7<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/7 (7 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/8<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/8 (13 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/9<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/9 (13 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/10<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/10 (6 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/11<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/11 (6 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/12<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/12 (10 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/13<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/13 (8 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/14<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/14 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/15<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/15 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/16<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/16 (6 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/17<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/17 (14 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/18<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/18 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/19<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/19 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/20<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/20 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/21<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/21 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/22<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/22 (9 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/23<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/23 (9 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/24<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/24 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/25<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/25 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/26<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/26 (6 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/27<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/27 (6 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/28<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/28 (3 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/29<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/29 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/30<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/30 (7 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/31<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/31 (14 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/32<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/32 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/33<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/33 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/34<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/34 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/35<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/35 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/36<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/36 (9 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/37<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/37 (8 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/38<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/38 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/39<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/39 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/40<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/40 (7 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/41<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/41 (6 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/42<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/42 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/43<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/43 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/44<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/44 (6 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/45<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/45 (14 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/46<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/46 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/47<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/47 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/48<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/48 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/49<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/49 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/50<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/50 (9 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/51<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/51 (8 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/52<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/52 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/53<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/53 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/54<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/54 (7 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/55<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/55 (6 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/56<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/56 (3 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/57<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/57 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/58<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/58 (6 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/59<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/59 (14 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/60<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/60 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/61<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/61 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/62<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/62 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/63<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/63 (5 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/64<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/64 (9 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/65<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/65 (9 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/66<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/66 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/67<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/67 (4 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/68<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/68 (7 ms)<br />
[ RUN      ] AV1/FilterIntraPredTest.RunCheckOutput/69<br />
[       OK ] AV1/FilterIntraPredTest.RunCheckOutput/69 (6 ms)<br />
[———-] 70 tests from AV1/FilterIntraPredTest (462 ms total)</p>

<p>[———-] Global test environment tear-down<br />
[==========] 70 tests from 1 test case ran. (463 ms total)<br />
[  PASSED  ] 70 tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ivy-zhang — APPROVED** [review]

**Comment by edmond-zhu** [comment]
@Cidana-Zhengwen please help review this PR.

**Review by Cidana-Zhengwen — APPROVED** [review]

**Comment by edmond-zhu** [comment]
merged

**Pull request closed without merging**
