### PR TITLE
Add wedge utils unit tests

### PR DESCRIPTION
**Pull request by Cidana-Developers**

### CODE REVIEW

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `test/CompoundUtilTest.cc`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### test/CompoundUtilTest.cc
```diff 
--- test/CompoundUtilTest.cc
+++ test/CompoundUtilTest.cc
@@ -129,5 +129,4 @@
     }
 }
 
-
 }  // namespace

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 33%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/FwdTxfm2dAsmTest.cc.o<br />
[ 38%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/FwdTxfm2dTest.cc.o<br />
[ 38%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/IntraBcUtilTest.cc.o<br />
[ 44%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm1dTest.cc.o<br />
[ 44%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm2dAsmTest.cc.o<br />
[ 44%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InversetransformTests.cc.o<br />
[ 50%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/MotionEstimationTest.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/MotionEstimationTest.cc:13:0:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbMeSadCalculation.h:143:35: warning: ‘initialize_buffer32bits_func_ptr_array’ defined but not used [-Wunused-variable]<br />
     static EbInializeBuffer32Bits initialize_buffer32bits_func_ptr_array[ASM_TYPE_TOTAL] = {<br />
                                   ^<br />
[ 50%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/NoiseExtractTest.cc.o<br />
[ 50%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PackUnPackTest.cc.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PackUnPackTest.cc:281:10: warning: ‘{anonymous}::TEST_CRASH_SIZES’ defined but not used [-Wunused-variable]<br />
 AreaSize TEST_CRASH_SIZES[] = {AreaSize(65, 64), AreaSize(5, 4)};<br />
          ^<br />
[ 55%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PictureAdditionTest.cc.o<br />
[ 55%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/QuantAsmTest.cc.o<br />
[ 55%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/ResidualTest.cc.o<br />
[ 61%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/RestorationPickTest.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/RestorationPickTest.cc:14:0:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/synonyms_avx2.h: In function ‘__m256i yy_load_256(const void<em>)’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/synonyms_avx2.h:26:48: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]<br />
 static INLINE __m256i yy_load_256(const void *a) {<br />
                                                ^<br />
[ 61%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SadTest.cc.o<br />
[ 61%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SelfGuidedUtilTest.cc.o<br />
[ 66%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SpatialFullDistortionTest.cc.o<br />
[ 66%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/TransposeTest.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/TransposeTest.cc:24:0:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/transpose_avx2.h: In function ‘__m256i _mm256_unpacklo_epi128(__m256i, __m256i)’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/transpose_avx2.h:24:63: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]<br />
                                              const __m256i in1) {<br />
                                                               ^<br />
[ 66%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/VarianceTest.cc.o<br />
[ 72%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/WedgeUtilTest.cc.o<br />
[ 72%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/compute_mean_test.cc.o<br />
[ 72%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/convolve_2d_test.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/convolve_avx2.h:18:0,<br />
                 from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/convolve_2d_test.cc:39:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h: In function ‘__m256i load_u8_4x4_avx2(const uint8_t</em>, uint32_t)’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h:26:26: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]<br />
     const uint32_t stride)<br />
                          ^<br />
[ 77%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/frame_error_test.cc.o<br />
[ 77%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/intrapred_cfl_test.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/intrapred_dr_test.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/intrapred_edge_filter_test.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/intrapred_test.cc.o<br />
[ 88%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/quantize_func_test.cc.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 33%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/FwdTxfm2dAsmTest.cc.o<br />
[ 38%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/FwdTxfm2dTest.cc.o<br />
[ 38%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/IntraBcUtilTest.cc.o<br />
[ 44%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm1dTest.cc.o<br />
[ 44%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm2dAsmTest.cc.o<br />
[ 44%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InversetransformTests.cc.o<br />
[ 50%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/MotionEstimationTest.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/MotionEstimationTest.cc:13:0:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbMeSadCalculation.h:143:35: warning: ‘initialize_buffer32bits_func_ptr_array’ defined but not used [-Wunused-variable]<br />
     static EbInializeBuffer32Bits initialize_buffer32bits_func_ptr_array[ASM_TYPE_TOTAL] = {<br />
                                   ^<br />
[ 50%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/NoiseExtractTest.cc.o<br />
[ 50%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PackUnPackTest.cc.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PackUnPackTest.cc:281:10: warning: ‘{anonymous}::TEST_CRASH_SIZES’ defined but not used [-Wunused-variable]<br />
 AreaSize TEST_CRASH_SIZES[] = {AreaSize(65, 64), AreaSize(5, 4)};<br />
          ^<br />
[ 55%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PictureAdditionTest.cc.o<br />
[ 55%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/QuantAsmTest.cc.o<br />
[ 55%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/ResidualTest.cc.o<br />
[ 61%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/RestorationPickTest.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/RestorationPickTest.cc:14:0:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/synonyms_avx2.h: In function ‘__m256i yy_load_256(const void<em>)’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/synonyms_avx2.h:26:48: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]<br />
 static INLINE __m256i yy_load_256(const void *a) {<br />
                                                ^<br />
[ 61%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SadTest.cc.o<br />
[ 61%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SelfGuidedUtilTest.cc.o<br />
[ 66%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SpatialFullDistortionTest.cc.o<br />
[ 66%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/TransposeTest.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/TransposeTest.cc:24:0:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/transpose_avx2.h: In function ‘__m256i _mm256_unpacklo_epi128(__m256i, __m256i)’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/transpose_avx2.h:24:63: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]<br />
                                              const __m256i in1) {<br />
                                                               ^<br />
[ 66%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/VarianceTest.cc.o<br />
[ 72%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/WedgeUtilTest.cc.o<br />
[ 72%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/compute_mean_test.cc.o<br />
[ 72%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/convolve_2d_test.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/convolve_avx2.h:18:0,<br />
                 from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/convolve_2d_test.cc:39:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h: In function ‘__m256i load_u8_4x4_avx2(const uint8_t</em>, uint32_t)’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h:26:26: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]<br />
     const uint32_t stride)<br />
                          ^<br />
[ 77%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/frame_error_test.cc.o<br />
[ 77%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/intrapred_cfl_test.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/intrapred_dr_test.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/intrapred_edge_filter_test.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/intrapred_test.cc.o<br />
[ 88%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/quantize_func_test.cc.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 11%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/AdaptiveScanTest.cc.o<br />
[ 16%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/BitstreamWriterTest.cc.o<br />
[ 16%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/CdefTest.cc.o<br />
[ 16%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/CompoundUtilTest.cc.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/CompoundUtilTest.cc: In member function ‘void {anonymous}::BuildCompDiffwtdMaskD16Test::run_test()’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/CompoundUtilTest.cc:325:25: error: ‘test_impl’ was not declared in this scope<br />
                       bd);<br />
                         ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/CompoundUtilTest.cc:283:37: warning: unused variable ‘tst_func’ [-Wunused-variable]<br />
         BuildCompDiffwtdMaskD16Func tst_func = TEST_GET_PARAM(1);<br />
                                     ^<br />
test/CMakeFiles/SvtAv1UnitTests.dir/build.make:127: recipe for target ‘test/CMakeFiles/SvtAv1UnitTests.dir/CompoundUtilTest.cc.o’ failed<br />
make[3]: <em>** [test/CMakeFiles/SvtAv1UnitTests.dir/CompoundUtilTest.cc.o] Error 1<br />
CMakeFiles/Makefile2:1644: recipe for target ‘test/CMakeFiles/SvtAv1UnitTests.dir/all’ failed<br />
make[2]: **</em> [test/CMakeFiles/SvtAv1UnitTests.dir/all] Error 2<br />
CMakeFiles/Makefile2:1656: recipe for target ‘test/CMakeFiles/SvtAv1UnitTests.dir/rule’ failed<br />
make[1]: *** [test/CMakeFiles/SvtAv1UnitTests.dir/rule] Error 2</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `test/CompoundUtilTest.cc`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### test/CompoundUtilTest.cc
```diff 
--- test/CompoundUtilTest.cc
+++ test/CompoundUtilTest.cc
@@ -314,15 +314,15 @@
                                                   bd);
 
             tst_func(mask_test,
-                      (DIFFWTD_MASK_TYPE)mask_type,
-                      src0,
-                      width,
-                      src1,
-                      width,
-                      height,
-                      width,
-                      &conv_params,
-                      bd);
+                     (DIFFWTD_MASK_TYPE)mask_type,
+                     src0,
+                     width,
+                     src1,
+                     width,
+                     height,
+                     width,
+                     &conv_params,
+                     bd);
 
             for (int r = 0; r < height; ++r) {
                 for (int c = 0; c < width; ++c) {

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `test/CompoundUtilTest.cc`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### test/CompoundUtilTest.cc
```diff 
--- test/CompoundUtilTest.cc
+++ test/CompoundUtilTest.cc
@@ -314,15 +314,15 @@
                                                   bd);
 
             tst_func(mask_test,
-                      (DIFFWTD_MASK_TYPE)mask_type,
-                      src0,
-                      width,
-                      src1,
-                      width,
-                      height,
-                      width,
-                      &conv_params,
-                      bd);
+                     (DIFFWTD_MASK_TYPE)mask_type,
+                     src0,
+                     width,
+                     src1,
+                     width,
+                     height,
+                     width,
+                     &conv_params,
+                     bd);
 
             for (int r = 0; r < height; ++r) {
                 for (int c = 0; c < width; ++c) {

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 78%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/FwdTxfm2dTest.cc.o<br />
[ 78%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/HbdVarianceTest.cc.o<br />
[ 79%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/IntraBcUtilTest.cc.o<br />
[ 79%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm1dTest.cc.o<br />
[ 79%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm2dAsmTest.cc.o<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InversetransformTests.cc.o<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/MotionEstimationTest.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/MotionEstimationTest.cc:13:0:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbMeSadCalculation.h:143:35: warning: ‘initialize_buffer32bits_func_ptr_array’ defined but not used [-Wunused-variable]<br />
     static EbInializeBuffer32Bits initialize_buffer32bits_func_ptr_array[ASM_TYPE_TOTAL] = {<br />
                                   ^<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/NoiseExtractTest.cc.o<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PackUnPackTest.cc.o<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PictureAdditionTest.cc.o<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/QuantAsmTest.cc.o<br />
[ 82%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/ResidualTest.cc.o<br />
[ 82%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/RestorationPickTest.cc.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by edmond-zhu** [comment]
merged

**Pull request closed without merging**
