### PR TITLE
Modify NoiseExtractTest

### PR DESCRIPTION
**Pull request by edmond-zhu**
1. add memory zero to fix NoiseExtractTest failure after optimized eb_picture_buffer_desc_dctor [PR1094]

### CODE REVIEW

**Comment by edmond-zhu** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*ExtractFilterTest*

**Comment by edmond-zhu** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*ExtractFilterTest*

**Comment by edmond-zhu** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*ExtractFilterTest*

**Comment by edmond-zhu** [comment]
Dry-run passed:
~~~
13:10:00 Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc
13:10:00 Note: Google Test filter = *ExtractFilterTest*
13:10:00 [==========] Running 5 tests from 1 test case.
13:10:00 [----------] Global test environment set-up.
13:10:00 [----------] 5 tests from ExtractFilterTest
13:10:00 [ RUN      ] ExtractFilterTest.LumaWeakNoiseTest
13:10:00 [       OK ] ExtractFilterTest.LumaWeakNoiseTest (14 ms)
13:10:00 [ RUN      ] ExtractFilterTest.LumaWeakNoiseSbTest
13:10:00 [       OK ] ExtractFilterTest.LumaWeakNoiseSbTest (9 ms)
13:10:00 [ RUN      ] ExtractFilterTest.LumaStrongNoiseTest
13:10:00 [       OK ] ExtractFilterTest.LumaStrongNoiseTest (11 ms)
13:10:00 [ RUN      ] ExtractFilterTest.ChromaWeakNoiseTest
13:10:00 [       OK ] ExtractFilterTest.ChromaWeakNoiseTest (9 ms)
13:10:00 [ RUN      ] ExtractFilterTest.ChromaStrongNoiseTest
13:10:00 [       OK ] ExtractFilterTest.ChromaStrongNoiseTest (11 ms)
13:10:00 [----------] 5 tests from ExtractFilterTest (54 ms total)
13:10:00 
13:10:00 [----------] Global test environment tear-down
13:10:00 [==========] 5 tests from 1 test case ran. (54 ms total)
13:10:00 [  PASSED  ] 5 tests.
~~~

**Comment by silverbacknet** [comment]
This just papers over the test failure. Whether the failure is because the encoding functions read out-of-bounds or the tests read out-of-bounds, the test should not be modified to ensure that out-of-bounds reads pass.

**Comment by edmond-zhu** [comment]
merged, close it

**Pull request closed without merging**
