### PR TITLE
Add OBMC variance unit test

### PR DESCRIPTION
**Pull request by edmond-zhu**
1. Add unit test for OBMC variance:
 - aom_obmc_variance{4-128}x{4-128}_{c, avx2}
 - aom_obmc_sub_pixel_variance{4-128}x{4-128}_{c, sse4_1

### CODE REVIEW

**Comment by edmond-zhu** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=OBMC/*

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 11%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPacketizationProcess.c.o<br />
[ 11%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPacketizationReorderQueue.c.o<br />
[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureAnalysisProcess.c.o<br />
[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureAnalysisResults.c.o<br />
[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureBufferDesc.c.o<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureControlSet.c.o<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionProcess.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbPictureDecisionProcess.c: In function ‘picture_decision_kernel’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbPictureDecisionProcess.c:3657:84: warning: array subscript is above array bounds [-Warray-bounds]<br />
                                         picture_control_set_ptr-&gt;temp_filt_pcs_list[pic_i + num_past_pics + 1] = pcs_itr;<br />
                                                                                    ^<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionQueue.c.o<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionReorderQueue.c.o<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionResults.c.o<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDemuxResults.c.o<br />
[ 15%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureManagerQueue.c.o<br />
[ 15%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureManagerReorderQueue.c.o<br />
–<br />
[ 79%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/FwdTxfm2dTest.cc.o<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/HbdVarianceTest.cc.o<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/IntraBcUtilTest.cc.o<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm1dTest.cc.o<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm2dAsmTest.cc.o<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InversetransformTests.cc.o<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/MotionEstimationTest.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/MotionEstimationTest.cc:12:0:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbMeSadCalculation.h:143:35: warning: ‘initialize_buffer32bits_func_ptr_array’ defined but not used [-Wunused-variable]<br />
     static EbInializeBuffer32Bits initialize_buffer32bits_func_ptr_array[ASM_TYPE_TOTAL] = {<br />
                                   ^<br />
[ 82%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/NoiseExtractTest.cc.o<br />
[ 82%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/OBMCVarianceTest.cc.o<br />
[ 82%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PackUnPackTest.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PictureAdditionTest.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PictureOperatorTest.cc.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc: In constructor ‘{anonymous}::PictureOperatorTest::PictureOperatorTest()’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc:215:25: warning: ‘{anonymous}::PictureOperatorTest::pu_height_’ will be initialized after [-Wreorder]<br />
     uint32<em>t pu_width</em>, pu_height_;<br />
                         ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc:214:17: warning:   ‘{anonymous}::TestPattern {anonymous}::PictureOperatorTest::test_pattern_’ [-Wreorder]<br />
     TestPattern test_pattern_;<br />
                 ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc:84:5: warning:   when initialized here [-Wreorder]<br />
     PictureOperatorTest()<br />
     ^<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PsnrTest.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/QuantAsmTest.cc.o<br />
[ 84%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/ResidualTest.cc.o<br />
[ 84%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/RestorationPickTest.cc.o<br />
[ 84%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SadTest.cc.o<br />
[ 85%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SelfGuidedUtilTest.cc.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = OBMC/*<br />
[==========] Running 44 tests from 2 test cases.<br />
[———-] Global test environment set-up.<br />
[———-] 22 tests from OBMC/OBMCVarianceTest<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/0<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/0 (1711 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/1<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/1 (1692 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/2<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/2 (1691 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/3<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/3 (1681 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/4<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/4 (1676 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/5<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/5 (1673 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/6<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/6 (1669 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/7<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/7 (1670 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/8<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/8 (1666 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/9<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/9 (1666 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/10<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/10 (1666 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/11<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/11 (1668 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/12<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/12 (1666 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/13<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/13 (1666 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/14<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/14 (1663 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/15<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/15 (1661 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/16<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/16 (1661 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/17<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/17 (1667 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/18<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/18 (1667 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/19<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/19 (1666 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/20<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/20 (1672 ms)<br />
[ RUN      ] OBMC/OBMCVarianceTest.RunCheckOutput/21<br />
[       OK ] OBMC/OBMCVarianceTest.RunCheckOutput/21 (1671 ms)<br />
[———-] 22 tests from OBMC/OBMCVarianceTest (36789 ms total)</p>

<p>[———-] 22 tests from OBMC/OBMCSubPixelVarianceTest<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/0<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/0 (1739 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/1<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/1 (1691 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/2<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/2 (1692 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/3<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/3 (1665 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/4<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/4 (1655 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/5<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/5 (1655 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/6<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/6 (1651 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/7<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/7 (1647 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/8<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/8 (1646 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/9<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/9 (1648 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/10<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/10 (1643 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/11<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/11 (1644 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/12<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/12 (1649 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/13<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/13 (1644 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/14<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/14 (1639 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/15<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/15 (1640 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/16<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/16 (1640 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/17<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/17 (1643 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/18<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/18 (1646 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/19<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/19 (1652 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/20<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/20 (1650 ms)<br />
[ RUN      ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/21<br />
[       OK ] OBMC/OBMCSubPixelVarianceTest.RunCheckOutput/21 (1651 ms)<br />
[———-] 22 tests from OBMC/OBMCSubPixelVarianceTest (36430 ms total)</p>

<p>[———-] Global test environment tear-down<br />
[==========] 44 tests from 2 test cases ran. (73220 ms total)<br />
[  PASSED  ] 44 tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by Cidana-Zhengwen — APPROVED** [review]

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 11%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPacketizationProcess.c.o<br />
[ 11%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPacketizationReorderQueue.c.o<br />
[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureAnalysisProcess.c.o<br />
[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureAnalysisResults.c.o<br />
[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureBufferDesc.c.o<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureControlSet.c.o<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionProcess.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbPictureDecisionProcess.c: In function ‘picture_decision_kernel’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbPictureDecisionProcess.c:3687:84: warning: array subscript is above array bounds [-Warray-bounds]<br />
                                         picture_control_set_ptr-&gt;temp_filt_pcs_list[pic_i + num_past_pics + 1] = pcs_itr;<br />
                                                                                    ^<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionQueue.c.o<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionReorderQueue.c.o<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionResults.c.o<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDemuxResults.c.o<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureManagerQueue.c.o<br />
[ 15%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureManagerReorderQueue.c.o<br />
–<br />
[ 78%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/FwdTxfm2dTest.cc.o<br />
[ 79%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/HbdVarianceTest.cc.o<br />
[ 79%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/IntraBcUtilTest.cc.o<br />
[ 79%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm1dTest.cc.o<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InvTxfm2dAsmTest.cc.o<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/InversetransformTests.cc.o<br />
[ 80%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/MotionEstimationTest.cc.o<br />
In file included from /home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/MotionEstimationTest.cc:12:0:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbMeSadCalculation.h:143:35: warning: ‘initialize_buffer32bits_func_ptr_array’ defined but not used [-Wunused-variable]<br />
     static EbInializeBuffer32Bits initialize_buffer32bits_func_ptr_array[ASM_TYPE_TOTAL] = {<br />
                                   ^<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/NoiseExtractTest.cc.o<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/OBMCVarianceTest.cc.o<br />
[ 81%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PackUnPackTest.cc.o<br />
[ 82%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PictureAdditionTest.cc.o<br />
[ 82%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PictureOperatorTest.cc.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc: In constructor ‘{anonymous}::PictureOperatorTest::PictureOperatorTest()’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc:215:25: warning: ‘{anonymous}::PictureOperatorTest::pu_height_’ will be initialized after [-Wreorder]<br />
     uint32<em>t pu_width</em>, pu_height_;<br />
                         ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc:214:17: warning:   ‘{anonymous}::TestPattern {anonymous}::PictureOperatorTest::test_pattern_’ [-Wreorder]<br />
     TestPattern test_pattern_;<br />
                 ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/PictureOperatorTest.cc:84:5: warning:   when initialized here [-Wreorder]<br />
     PictureOperatorTest()<br />
     ^<br />
[ 82%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PsnrTest.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/QuantAsmTest.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/ResidualTest.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/RestorationPickTest.cc.o<br />
[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SadTest.cc.o<br />
[ 84%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SelfGuidedUtilTest.cc.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by edmond-zhu** [comment]
merged

**Pull request closed without merging**
