### PR TITLE
Add more test cases for deblocking test

### PR DESCRIPTION
**Pull request by edmond-zhu**
add more test cases for deblocking:
 - aom_lpf_{horizontal, vertical}_{4, 6, 8}_sse2
 - aom_highbd_lpf_{horizontal, vertical}_{4, 8}_sse2

### CODE REVIEW

**Comment by edmond-zhu** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*LoopFilterTest*

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest-all.cc.o<br />
[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest_main.cc.o<br />
[ 59%] Linking CXX shared library ../../../../../Bin/Release/libgtest_all.so<br />
[ 59%] Built target gtest_all<br />
Scanning dependencies of target SvtAv1UnitTests<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘update_mi_map’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1614:76: warning: ‘*((void *)&amp;rf+1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[1] =<br />
                                                                            ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1613:76: warning: ‘rf’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[0] = rf[0];<br />
                                                                            ^<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbBlend_a64_mask.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCdef.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCdefProcess.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCodingLoop.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCodingUnit.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbDeblockingFilter.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>LoopFilterTest</em><br />
[==========] Running 31 tests from 2 test cases.<br />
[———-] Global test environment set-up.<br />
[———-] 7 tests from SSE2/LbdLoopFilterTest<br />
[ RUN      ] SSE2/LbdLoopFilterTest.MatchTestRandomData/0<br />
[       OK ] SSE2/LbdLoopFilterTest.MatchTestRandomData/0 (118 ms)<br />
[ RUN      ] SSE2/LbdLoopFilterTest.MatchTestRandomData/1<br />
[       OK ] SSE2/LbdLoopFilterTest.MatchTestRandomData/1 (118 ms)<br />
[ RUN      ] SSE2/LbdLoopFilterTest.MatchTestRandomData/2<br />
[       OK ] SSE2/LbdLoopFilterTest.MatchTestRandomData/2 (118 ms)<br />
[ RUN      ] SSE2/LbdLoopFilterTest.MatchTestRandomData/3<br />
[       OK ] SSE2/LbdLoopFilterTest.MatchTestRandomData/3 (119 ms)<br />
[ RUN      ] SSE2/LbdLoopFilterTest.MatchTestRandomData/4<br />
[       OK ] SSE2/LbdLoopFilterTest.MatchTestRandomData/4 (118 ms)<br />
[ RUN      ] SSE2/LbdLoopFilterTest.MatchTestRandomData/5<br />
[       OK ] SSE2/LbdLoopFilterTest.MatchTestRandomData/5 (120 ms)<br />
[ RUN      ] SSE2/LbdLoopFilterTest.MatchTestRandomData/6<br />
[       OK ] SSE2/LbdLoopFilterTest.MatchTestRandomData/6 (120 ms)<br />
[———-] 7 tests from SSE2/LbdLoopFilterTest (831 ms total)</p>

<p>[———-] 24 tests from SSE2/HbdLoopFilterTest<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/0<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/0 (118 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/1<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/1 (119 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/2<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/2 (119 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/3<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/3 (120 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/4<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/4 (118 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/5<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/5 (119 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/6<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/6 (119 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/7<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/7 (120 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/8<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/8 (118 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/9<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/9 (119 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/10<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/10 (119 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/11<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/11 (120 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/12<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/12 (118 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/13<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/13 (118 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/14<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/14 (119 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/15<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/15 (120 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/16<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/16 (118 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/17<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/17 (118 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/18<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/18 (119 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/19<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/19 (120 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/20<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/20 (118 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/21<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/21 (119 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/22<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/22 (119 ms)<br />
[ RUN      ] SSE2/HbdLoopFilterTest.MatchTestRandomData/23<br />
[       OK ] SSE2/HbdLoopFilterTest.MatchTestRandomData/23 (119 ms)<br />
[———-] 24 tests from SSE2/HbdLoopFilterTest (2853 ms total)</p>

<p>[———-] Global test environment tear-down<br />
[==========] 31 tests from 2 test cases ran. (3684 ms total)<br />
[  PASSED  ] 31 tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by Richard-li — CHANGES_REQUESTED** [review]
dry_run_test failed?

**Comment by edmond-zhu** [comment]
duplicated, close it

**Pull request closed without merging**
