### PR TITLE
Fix eight horizontal sad test

### PR DESCRIPTION
**Pull request by ivy-zhang**

### CODE REVIEW

**Comment by Cidana-Developers** [comment]
Can one of the admins verify this patch?

**Comment by ivy-zhang** [comment]
# Pr for fix eight horizontal sad test
## Check result
  1. clang-format: OK
  2. local build result:
    + windows:
	  warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 

    + linux:
      CMake Error #1 :
 ```
      CMake Error at /opt/work/sad/SVT-AV1/test/e2e_test/test_data_util.cmake:76 (file):
  file DOWNLOAD HASH mismatch

    for file: [/opt/work/sad/SVT-AV1/test/e2e_test/../vectors//niklas_640_480_30.yuv]
      expected hash: [70894878d916a599842d9ad0dcd24e10c13e5467]
        actual hash: [214740dc3fed5dab1df5f3b19e6208f1bed4aa87]
             status: [18;"Transferred a partial file"]
```
      
  3. remote build result:
    + travis: 
            a. mac: `-pie being ignored. It is only used when linking a main executable`, can be ignored.
            b.linux: No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself
    + appvedor:
             a.no warnings    
## Test Plan: 
  Run the unit test with `./SvtAv1UnitTest --gtest_filter="*EIGHTSAD"`, and check the result
## Dry-run result:
```
Running main() from C:\Users\Ryan\realgit\SVT-AV1\third_party\googletest\src\gtest_main.cc
Note: Google Test filter = *EIGHTSAD*
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from EIGHTSAD/GetEightSadTest
[ RUN      ] EIGHTSAD/GetEightSadTest.GetEightSadTest/0
[       OK ] EIGHTSAD/GetEightSadTest.GetEightSadTest/0 (0 ms)
[ RUN      ] EIGHTSAD/GetEightSadTest.GetEightSadTest/1
[       OK ] EIGHTSAD/GetEightSadTest.GetEightSadTest/1 (0 ms)
[ RUN      ] EIGHTSAD/GetEightSadTest.GetEightSadTest/2
[       OK ] EIGHTSAD/GetEightSadTest.GetEightSadTest/2 (14 ms)
[ RUN      ] EIGHTSAD/GetEightSadTest.GetEightSadTest/3
[       OK ] EIGHTSAD/GetEightSadTest.GetEightSadTest/3 (14 ms)
[----------] 4 tests from EIGHTSAD/GetEightSadTest (31 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (38 ms total)
[  PASSED  ] 4 tests.
```

**Review by Cidana-Developers — APPROVED** [review]
@Ivy
 请foch 验证下

**Comment by Cidana-Developers** [comment]
Merged.

**Pull request closed without merging**
