### PR TITLE
Add FFT and iFFT unit test

### PR DESCRIPTION
**Pull request by edmond-zhu**
a. Add unit test for FFT and iFFT

### CODE REVIEW

**Comment by edmond-zhu** [comment]
# For FFT/iFFT 2d unit test

# Pr for add FFT/iFFT 2d unit test
## license: check if license is ok
## Comments
## warnings in Local build
1. mac: no new warning, only warning: -pie being ignored. It is only used when linking a main executable
2. linux: GNU warning in SpatialFullDistortionTest.cc
3. windows: none

## warnings on remote ci servers
1. jenkins:
a. clang-format
b. 
2. travis
  a. mac: `-pie being ignored. It is only used when linking a main executable`, can be ignored.
  b. linux: SpaticalFullDistoration wanring, could be fixed by merge the latest code;
3. appvedor
  a. no warnings

## dry run output
~~~
Running main() from C:\Works\AV1\SVT-AV1\third_party\googletest\src\gtest_main.cc
Note: Google Test filter = FFT/*.*
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 10 tests from FFT/FFT2DTest
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/0
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/0 (9 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/1
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/1 (36 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/2
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/2 (160 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/3
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/3 (687 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/4
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/4 (3006 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/0
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/0 (6 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/1
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/1 (20 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/2
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/2 (88 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/3
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/3 (341 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/4
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/4 (1333 ms)
[----------] 10 tests from FFT/FFT2DTest (5697 ms total)

[----------] Global test environment tear-down
[==========] 10 tests from 1 test case ran. (5703 ms total)
[  PASSED  ] 10 tests.
~~~

**Review by Cidana-Developers — APPROVED** [review]

**Comment by edmond-zhu** [comment]
@FochQu  please help verify the dry run results with command:
~~~
SvtAv1UnitTests --gtest_filter=FFT/*.*
~~~

**Comment by FochQu** [comment]
Running main() from /home/jenkins/test/SVT-AV1/third_party/googletest/src/gtest_main.cc
Note: Google Test filter = */FFT2DTest.*
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 10 tests from FFT/FFT2DTest
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/0
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/0 (2 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/1
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/1 (4 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/2
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/2 (15 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/3
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/3 (62 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/4
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/4 (248 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/0
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/0 (1 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/1
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/1 (3 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/2
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/2 (9 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/3
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/3 (36 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/4
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/4 (137 ms)
[----------] 10 tests from FFT/FFT2DTest (518 ms total)

[----------] Global test environment tear-down
[==========] 10 tests from 1 test case ran. (518 ms total)
[  PASSED  ] 10 tests.

**Review by FochQu — APPROVED** [review]
Branch for add_fft_ifft_test
--
+Linux:
test/CMakeFiles/SvtAv1UnitTests.dir/build.make:140: recipe for target 'test/CMakeFiles/SvtAv1UnitTests.dir/DenoiseTest.cc.o' failed
make[3]: *** [test/CMakeFiles/SvtAv1UnitTests.dir/DenoiseTest.cc.o] Error 1
CMakeFiles/Makefile2:1644: recipe for target 'test/CMakeFiles/SvtAv1UnitTests.dir/all' failed
make[2]: *** [test/CMakeFiles/SvtAv1UnitTests.dir/all] Error 2
CMakeFiles/Makefile2:1656: recipe for target 'test/CMakeFiles/SvtAv1UnitTests.dir/rule' failed
make[1]: *** [test/CMakeFiles/SvtAv1UnitTests.dir/rule] Error 2
Makefile:682: recipe for target 'SvtAv1UnitTests' failed
make: *** [SvtAv1UnitTests] Error 2

+Mac
ld: warning: -pie being ignored. It is only used when linking a main executable

+Windows
no warning

dry run test
--
jenkins@jenkins-agent:~/test/SVT-AV1/Bin/Release$ ./SvtAv1UnitTests --gtest_filter="FFT/*.*"
Running main() from /home/jenkins/test/SVT-AV1/third_party/googletest/src/gtest_main.cc
Note: Google Test filter = FFT/*.*
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 10 tests from FFT/FFT2DTest
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/0
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/0 (1 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/1
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/1 (4 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/2
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/2 (16 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/3
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/3 (61 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/4
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/4 (248 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/0
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/0 (1 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/1
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/1 (3 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/2
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/2 (9 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/3
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/3 (35 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/4
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/4 (137 ms)
[----------] 10 tests from FFT/FFT2DTest (515 ms total)

[----------] Global test environment tear-down
[==========] 10 tests from 1 test case ran. (516 ms total)
[  PASSED  ] 10 tests.

**Comment by Cidana-Developers** [comment]
Merged.

**Pull request closed without merging**
