### PR TITLE
Add hb temporal filter test

### PR DESCRIPTION
**Pull request by ivy-zhang**

### CODE REVIEW

**Comment by Cidana-Developers** [comment]
Can one of the admins verify this patch?

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `test/TemporalFilterTest.cc`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### test/TemporalFilterTest.cc
```diff 
--- test/TemporalFilterTest.cc
+++ test/TemporalFilterTest.cc
@@ -34,16 +34,13 @@
     uint32_t *y_accum, uint16_t *y_count, uint32_t *u_accum, uint16_t *u_count,
     uint32_t *v_accum, uint16_t *v_count);
 void svt_av1_apply_filtering_c(
-    const uint8_t *y_src, int y_src_stride,
-                       const uint8_t *y_pre, int y_pre_stride,
-                       const uint8_t *u_src, const uint8_t *v_src,
-                       int uv_src_stride, const uint8_t *u_pre,
-                       const uint8_t *v_pre, int uv_pre_stride,
-                       unsigned int block_width, unsigned int block_height,
-                       int ss_x, int ss_y, int strength, const int *blk_fw,
-                       int use_whole_blk, uint32_t *y_accum, uint16_t *y_count,
-                       uint32_t *u_accum, uint16_t *u_count, uint32_t *v_accum,
-                       uint16_t *v_count);
+    const uint8_t *y_src, int y_src_stride, const uint8_t *y_pre,
+    int y_pre_stride, const uint8_t *u_src, const uint8_t *v_src,
+    int uv_src_stride, const uint8_t *u_pre, const uint8_t *v_pre,
+    int uv_pre_stride, unsigned int block_width, unsigned int block_height,
+    int ss_x, int ss_y, int strength, const int *blk_fw, int use_whole_blk,
+    uint32_t *y_accum, uint16_t *y_count, uint32_t *u_accum, uint16_t *u_count,
+    uint32_t *v_accum, uint16_t *v_count);
 }
 
 using svt_av1_test_tool::SVTRandom;  // to generate the random
@@ -59,7 +56,7 @@
 static const uint32_t index_16x16_from_subindexes[4][4] = {
     {0, 1, 4, 5}, {2, 3, 6, 7}, {8, 9, 12, 13}, {10, 11, 14, 15}};
 
-const int stride_pred_[COLOR_CHANNELS] = {BW, BW>>1, BW>>1};
+const int stride_pred_[COLOR_CHANNELS] = {BW, BW >> 1, BW >> 1};
 const int ALTREF_STRENGTH[] = {0, 1, 2, 3, 4, 5, 6};
 
 typedef std::tuple<BlockIndex, FilterWeightPattern, int> TestParam;
@@ -223,7 +220,7 @@
         pred_ptr_[C_U] = pred_[C_U] + offset_block_buffer_U;
         pred_ptr_[C_V] = pred_[C_V] + offset_block_buffer_V;
 
-		hbd_src_ptr_[C_Y] = hbd_src_[C_Y] + offset_src_buffer_Y;
+        hbd_src_ptr_[C_Y] = hbd_src_[C_Y] + offset_src_buffer_Y;
         hbd_src_ptr_[C_U] = hbd_src_[C_U] + offset_src_buffer_U;
         hbd_src_ptr_[C_V] = hbd_src_[C_V] + offset_src_buffer_V;
 
@@ -321,74 +318,74 @@
             prepare_data();
             init_param();
             svt_av1_apply_filtering_c(src_ptr_[C_Y],
-                              stride_[C_Y],
-                              pred_ptr_[C_Y],
-                              stride_pred_[C_Y],
-                              src_ptr_[C_U],
-                              src_ptr_[C_V],
-                              stride_[C_U],
-                              pred_ptr_[C_U],
-                              pred_ptr_[C_V],
-                              stride_pred_[C_U],
-                              block_width_,
-                              block_height_,
-                              ss_x_,
-                              ss_y_,
-                              altref_strength_,
-                              blk_fw_32x32_,
-                              0,  // use_32x32
-                              accum_ptr1_[C_Y],
-                              count_ptr1_[C_Y],
-                              accum_ptr1_[C_U],
-                              count_ptr1_[C_U],
-                              accum_ptr1_[C_V],
-                              count_ptr1_[C_V]);
+                                      stride_[C_Y],
+                                      pred_ptr_[C_Y],
+                                      stride_pred_[C_Y],
+                                      src_ptr_[C_U],
+                                      src_ptr_[C_V],
+                                      stride_[C_U],
+                                      pred_ptr_[C_U],
+                                      pred_ptr_[C_V],
+                                      stride_pred_[C_U],
+                                      block_width_,
+                                      block_height_,
+                                      ss_x_,
+                                      ss_y_,
+                                      altref_strength_,
+                                      blk_fw_32x32_,
+                                      0,  // use_32x32
+                                      accum_ptr1_[C_Y],
+                                      count_ptr1_[C_Y],
+                                      accum_ptr1_[C_U],
+                                      count_ptr1_[C_U],
+                                      accum_ptr1_[C_V],
+                                      count_ptr1_[C_V]);
             svt_av1_apply_temporal_filter_sse4_1(src_ptr_[C_Y],
-                                             stride_[C_Y],
-                                             pred_ptr_[C_Y],
-                                             stride_pred_[C_Y],
-                                             src_ptr_[C_U],
-                                             src_ptr_[C_V],
-                                             stride_[C_U],
-                                             pred_ptr_[C_U],
-                                             pred_ptr_[C_V],
-                                             stride_pred_[C_U],
-                                             block_width_,
-                                             block_height_,
-                                             ss_x_,
-                                             ss_y_,
-                                             altref_strength_,
-                                             blk_fw_32x32_,
-                                             0,  // use_32x32
-                                             accum_ptr2_[C_Y],
-                                             count_ptr2_[C_Y],
-                                             accum_ptr2_[C_U],
-                                             count_ptr2_[C_U],
-                                             accum_ptr2_[C_V],
-                                             count_ptr2_[C_V]);
+                                                 stride_[C_Y],
+                                                 pred_ptr_[C_Y],
+                                                 stride_pred_[C_Y],
+                                                 src_ptr_[C_U],
+                                                 src_ptr_[C_V],
+                                                 stride_[C_U],
+                                                 pred_ptr_[C_U],
+                                                 pred_ptr_[C_V],
+                                                 stride_pred_[C_U],
+                                                 block_width_,
+                                                 block_height_,
+                                                 ss_x_,
+                                                 ss_y_,
+                                                 altref_strength_,
+                                                 blk_fw_32x32_,
+                                                 0,  // use_32x32
+                                                 accum_ptr2_[C_Y],
+                                                 count_ptr2_[C_Y],
+                                                 accum_ptr2_[C_U],
+                                                 count_ptr2_[C_U],
+                                                 accum_ptr2_[C_V],
+                                                 count_ptr2_[C_V]);
             svt_av1_highbd_apply_temporal_filter_sse4_1(hbd_src_ptr_[C_Y],
-                                             stride_[C_Y],
-                                             hbd_pred_ptr_[C_Y],
-                                             stride_pred_[C_Y],
-                                             hbd_src_ptr_[C_U],
-                                             hbd_src_ptr_[C_V],
-                                             stride_[C_U],
-                                             hbd_pred_ptr_[C_U],
-                                             hbd_pred_ptr_[C_V],
-                                             stride_pred_[C_U],
-                                             block_width_,
-                                             block_height_,
-                                             ss_x_,
-                                             ss_y_,
-                                             altref_strength_,
-                                             blk_fw_32x32_,
-                                             0,  // use_32x32
-                                             accum_ptr3_[C_Y],
-                                             count_ptr3_[C_Y],
-                                             accum_ptr3_[C_U],
-                                             count_ptr3_[C_U],
-                                             accum_ptr3_[C_V],
-                                             count_ptr3_[C_V]);
+                                                        stride_[C_Y],
+                                                        hbd_pred_ptr_[C_Y],
+                                                        stride_pred_[C_Y],
+                                                        hbd_src_ptr_[C_U],
+                                                        hbd_src_ptr_[C_V],
+                                                        stride_[C_U],
+                                                        hbd_pred_ptr_[C_U],
+                                                        hbd_pred_ptr_[C_V],
+                                                        stride_pred_[C_U],
+                                                        block_width_,
+                                                        block_height_,
+                                                        ss_x_,
+                                                        ss_y_,
+                                                        altref_strength_,
+                                                        blk_fw_32x32_,
+                                                        0,  // use_32x32
+                                                        accum_ptr3_[C_Y],
+                                                        count_ptr3_[C_Y],
+                                                        accum_ptr3_[C_U],
+                                                        count_ptr3_[C_U],
+                                                        accum_ptr3_[C_V],
+                                                        count_ptr3_[C_V]);
             check_accum_output();
             check_count_output();
             EXPECT_FALSE(HasFailure());

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `test/TemporalFilterTest.cc`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### test/TemporalFilterTest.cc
```diff 
--- test/TemporalFilterTest.cc
+++ test/TemporalFilterTest.cc
@@ -34,16 +34,13 @@
     uint32_t *y_accum, uint16_t *y_count, uint32_t *u_accum, uint16_t *u_count,
     uint32_t *v_accum, uint16_t *v_count);
 void svt_av1_apply_filtering_c(
-    const uint8_t *y_src, int y_src_stride,
-    const uint8_t *y_pre, int y_pre_stride,
-    const uint8_t *u_src, const uint8_t *v_src,
-    int uv_src_stride, const uint8_t *u_pre,
-    const uint8_t *v_pre, int uv_pre_stride,
-    unsigned int block_width, unsigned int block_height,
-    int ss_x, int ss_y, int strength, const int *blk_fw,
-    int use_whole_blk, uint32_t *y_accum, uint16_t *y_count,
-    uint32_t *u_accum, uint16_t *u_count, uint32_t *v_accum,
-    uint16_t *v_count);
+    const uint8_t *y_src, int y_src_stride, const uint8_t *y_pre,
+    int y_pre_stride, const uint8_t *u_src, const uint8_t *v_src,
+    int uv_src_stride, const uint8_t *u_pre, const uint8_t *v_pre,
+    int uv_pre_stride, unsigned int block_width, unsigned int block_height,
+    int ss_x, int ss_y, int strength, const int *blk_fw, int use_whole_blk,
+    uint32_t *y_accum, uint16_t *y_count, uint32_t *u_accum, uint16_t *u_count,
+    uint32_t *v_accum, uint16_t *v_count);
 }
 
 using svt_av1_test_tool::SVTRandom;  // to generate the random

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by edmond-zhu — APPROVED** [review]

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPacketizationProcess.c.o<br />
[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPacketizationReorderQueue.c.o<br />
[ 12%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureAnalysisProcess.c.o<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureAnalysisResults.c.o<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureBufferDesc.c.o<br />
[ 13%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureControlSet.c.o<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionProcess.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbPictureDecisionProcess.c: In function ‘picture_decision_kernel’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Common/Codec/EbPictureDecisionProcess.c:3577:84: warning: array subscript is above array bounds [-Warray-bounds]<br />
                                         picture_control_set_ptr-&gt;temp_filt_pcs_list[pic_i + num_past_pics + 1] = pcs_itr;<br />
                                                                                    ^<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionQueue.c.o<br />
[ 14%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionReorderQueue.c.o<br />
[ 15%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDecisionResults.c.o<br />
[ 15%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureDemuxResults.c.o<br />
[ 15%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureManagerQueue.c.o<br />
[ 16%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbPictureManagerReorderQueue.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by edmond-zhu** [comment]
merged

**Pull request closed without merging**
