### PR TITLE
Coveralls unittests

### PR DESCRIPTION
**Pull request by edmond-zhu**

### CODE REVIEW

**Comment by edmond-zhu** [comment]
coverage_test @./generate_report.sh

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 83%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PictureAdditionTest.cc.o<br />
[ 84%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PictureOperatorTest.cc.o<br />
[ 84%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/PsnrTest.cc.o<br />
[ 84%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/QuantAsmTest.cc.o<br />
[ 84%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/ResidualTest.cc.o<br />
[ 85%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/RestorationPickTest.cc.o<br />
[ 85%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SadTest.cc.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/SadTest.cc: In member function ‘void {anonymous}::SADTestSubSample::check_sad()’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/SadTest.cc:378:18: warning: variable ‘ref_sad’ set but not used [-Wunused-but-set-variable]<br />
         uint32_t ref_sad = 0;<br />
                  ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/SadTest.cc: In member function ‘void {anonymous}::SADTest::check_sad()’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/SadTest.cc:450:18: warning: variable ‘ref_sad’ set but not used [-Wunused-but-set-variable]<br />
         uint32_t ref_sad = 0;<br />
                  ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/SadTest.cc: In member function ‘void {anonymous}::SADAvgTest::check_sad_avg()’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/test/SadTest.cc:518:18: warning: variable ‘ref_sad’ set but not used [-Wunused-but-set-variable]<br />
         uint32_t ref_sad = 0;<br />
                  ^<br />
[ 85%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SelfGuidedUtilTest.cc.o<br />
[ 86%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/SpatialFullDistortionTest.cc.o<br />
[ 86%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/TemporalFilterTest.cc.o<br />
[ 86%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/TestEnv.c.o<br />
[ 86%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/TransposeTest.cc.o<br />
[ 87%] Building CXX object test/CMakeFiles/SvtAv1UnitTests.dir/VarianceTest.cc.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by edmond-zhu** [comment]
coverage_test @./generate_report.sh

**Comment by FochQu** [comment]
coverage_test @./generate_report.sh

**Comment by FochQu** [comment]
coverage_test @./generate_report.sh

**Comment by FochQu** [comment]
coverage_test @./generate_report.sh

**Comment by FochQu** [comment]
coverage_test @./generate_report.sh

**Comment by FochQu** [comment]
coverage_test @./generate_report.sh

**Pull request closed without merging**
