### PR TITLE
Noise extract unit tests

### PR DESCRIPTION
**Pull request by Cidana-Developers**

### CODE REVIEW

**Comment by Cidana-Developers** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Extract*

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Extract</em><br />
[==========] Running 1 test from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 1 test from ExtractFilterTest<br />
[ RUN      ] ExtractFilterTest.LumaWeakNoiseTest<br />
[       OK ] ExtractFilterTest.LumaWeakNoiseTest (5 ms)<br />
[———-] 1 test from ExtractFilterTest (5 ms total)</p>

<p>[———-] Global test environment tear-down<br />
[==========] 1 test from 1 test case ran. (5 ms total)<br />
[  PASSED  ] 1 test.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ivy-zhang** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Extract*

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Extract</em><br />
[==========] Running 5 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 5 tests from ExtractFilterTest<br />
[ RUN      ] ExtractFilterTest.LumaWeakNoiseTest<br />
[       OK ] ExtractFilterTest.LumaWeakNoiseTest (4 ms)<br />
[ RUN      ] ExtractFilterTest.LumaWeakNoiseLcuTest<br />
[       OK ] ExtractFilterTest.LumaWeakNoiseLcuTest (3 ms)<br />
[ RUN      ] ExtractFilterTest.LumaStrongNoiseTest<br />
[       OK ] ExtractFilterTest.LumaStrongNoiseTest (4 ms)<br />
[ RUN      ] ExtractFilterTest.ChromaWeakNoiseTest<br />
[       OK ] ExtractFilterTest.ChromaWeakNoiseTest (3 ms)<br />
[ RUN      ] ExtractFilterTest.ChromaStrongNoiseTest<br />
[       OK ] ExtractFilterTest.ChromaStrongNoiseTest (4 ms)<br />
[———-] 5 tests from ExtractFilterTest (18 ms total)</p>

<p>[———-] Global test environment tear-down<br />
[==========] 5 tests from 1 test case ran. (18 ms total)<br />
[  PASSED  ] 5 tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ivy-zhang** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Extract*

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `test/NoiseExtractTest.cc`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### test/NoiseExtractTest.cc
```diff 
--- test/NoiseExtractTest.cc
+++ test/NoiseExtractTest.cc
@@ -200,8 +200,7 @@
         // TODO: check more values of sb_origin_y and sb_origin_x;
         int sb_origin_y = 0;
         int sb_origin_x = 0;
-        noise_extract_luma_strong(
-            &in_pic_, &denoised_pic_ref_, 0, 0);
+        noise_extract_luma_strong(&in_pic_, &denoised_pic_ref_, 0, 0);
         noise_extract_luma_strong_avx2_intrin(
             &in_pic_, &denoised_pic_tst_, 0, 0);
 
@@ -222,8 +221,7 @@
         // TODO: check more values of sb_origin_y and sb_origin_x;
         int sb_origin_y = 0;
         int sb_origin_x = 0;
-        noise_extract_chroma_weak(
-            &in_pic_, &denoised_pic_ref_, 0, 0);
+        noise_extract_chroma_weak(&in_pic_, &denoised_pic_ref_, 0, 0);
         noise_extract_chroma_weak_avx2_intrin(
             &in_pic_, &denoised_pic_tst_, 0, 0);
 
@@ -258,6 +256,7 @@
             << "noise pic different with dim [" << width_ << " x " << height_
             << "] sb_origin [" << sb_origin_x << " x " << sb_origin_y << "]";
     }
+
   protected:
     uint32_t width_;
     uint32_t height_;

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ivy-zhang** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Extract*

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Extract</em><br />
[==========] Running 5 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 5 tests from ExtractFilterTest<br />
[ RUN      ] ExtractFilterTest.LumaWeakNoiseTest<br />
[       OK ] ExtractFilterTest.LumaWeakNoiseTest (3 ms)<br />
[ RUN      ] ExtractFilterTest.LumaWeakNoiseLcuTest<br />
[       OK ] ExtractFilterTest.LumaWeakNoiseLcuTest (4 ms)<br />
[ RUN      ] ExtractFilterTest.LumaStrongNoiseTest<br />
[       OK ] ExtractFilterTest.LumaStrongNoiseTest (3 ms)<br />
[ RUN      ] ExtractFilterTest.ChromaWeakNoiseTest<br />
[       OK ] ExtractFilterTest.ChromaWeakNoiseTest (4 ms)<br />
[ RUN      ] ExtractFilterTest.ChromaStrongNoiseTest<br />
[       OK ] ExtractFilterTest.ChromaStrongNoiseTest (3 ms)<br />
[———-] 5 tests from ExtractFilterTest (17 ms total)</p>

<p>[———-] Global test environment tear-down<br />
[==========] 5 tests from 1 test case ran. (18 ms total)<br />
[  PASSED  ] 5 tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Extract</em><br />
[==========] Running 5 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 5 tests from ExtractFilterTest<br />
[ RUN      ] ExtractFilterTest.LumaWeakNoiseTest<br />
[       OK ] ExtractFilterTest.LumaWeakNoiseTest (3 ms)<br />
[ RUN      ] ExtractFilterTest.LumaWeakNoiseLcuTest<br />
[       OK ] ExtractFilterTest.LumaWeakNoiseLcuTest (4 ms)<br />
[ RUN      ] ExtractFilterTest.LumaStrongNoiseTest<br />
[       OK ] ExtractFilterTest.LumaStrongNoiseTest (3 ms)<br />
[ RUN      ] ExtractFilterTest.ChromaWeakNoiseTest<br />
[       OK ] ExtractFilterTest.ChromaWeakNoiseTest (4 ms)<br />
[ RUN      ] ExtractFilterTest.ChromaStrongNoiseTest<br />
[       OK ] ExtractFilterTest.ChromaStrongNoiseTest (3 ms)<br />
[———-] 5 tests from ExtractFilterTest (17 ms total)</p>

<p>[———-] Global test environment tear-down<br />
[==========] 5 tests from 1 test case ran. (18 ms total)<br />
[  PASSED  ] 5 tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Extract*

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
      <tr>
        <td>:warning:</td>
        <td>
        Danger found 1 violations with this PR. Due to GitHub's max issue comment size, the number shown has been truncated to 0.
        </td>
      </tr>
  </tbody>
</table>

### Tests: 

Name | Status | Time | Classname|
--- | --- | --- | ---|
LumaWeakNoiseTest | run | 0.016 | ExtractFilterTest|
LumaStrongNoiseTest | run | 0.013 | ExtractFilterTest|
ChromaWeakNoiseTest | run | 0.017 | ExtractFilterTest|
ChromaStrongNoiseTest | run | 0.018 | ExtractFilterTest|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
merged, close it.

**Comment by Cidana-Emma** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Extract*

**Comment by FochQu** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Extract*

**Comment by FochQu** [comment]
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Extract*

**Pull request closed without merging**
