### PR TITLE
Merged e2e tests from PR#992 (https://github.com/OpenVisualCloud/SVT-…

### PR DESCRIPTION
**Pull request by edmond-zhu**
…AV1/pull/992)

### CODE REVIEW

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `test/api_test/SvtAv1EncParamsTest.cc`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### test/api_test/SvtAv1EncParamsTest.cc
```diff 
--- test/api_test/SvtAv1EncParamsTest.cc
+++ test/api_test/SvtAv1EncParamsTest.cc
@@ -355,8 +355,8 @@
 PARAM_TEST(EncParamHighDynamicRangeInputTest);
 
 /** Test case for profile, requiure YUV 422 or 444 which is unsupported now */
-//DEFINE_PARAM_TEST_CLASS(EncParamProfileTest, profile);
-//PARAM_TEST(EncParamProfileTest);
+// DEFINE_PARAM_TEST_CLASS(EncParamProfileTest, profile);
+// PARAM_TEST(EncParamProfileTest);
 
 /** Test case for tier*/
 DEFINE_PARAM_TEST_CLASS(EncParamTierTest, tier);

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by edmond-zhu** [comment]
dry_run_test @./Bin/Release/SvtAv1E2ETests

**Comment by edmond-zhu** [comment]
dry_run_test @./Bin/Release/SvtAv1E2ETests

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest-all.cc.o<br />
[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest_main.cc.o<br />
[ 59%] Linking CXX shared library ../../../../../Bin/Release/libgtest_all.so<br />
[ 59%] Built target gtest_all<br />
Scanning dependencies of target SvtAv1UnitTests<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘update_mi_map’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1614:76: warning: ‘*((void *)&amp;rf+1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[1] =<br />
                                                                            ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1613:76: warning: ‘rf’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[0] = rf[0];<br />
                                                                            ^<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbBlend_a64_mask.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCdef.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCdefProcess.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCodingLoop.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCodingUnit.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbDeblockingFilter.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest-all.cc.o<br />
[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest_main.cc.o<br />
[ 59%] Linking CXX shared library ../../../../../Bin/Release/libgtest_all.so<br />
[ 59%] Built target gtest_all<br />
Scanning dependencies of target SvtAv1UnitTests<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘update_mi_map’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1614:76: warning: ‘*((void *)&amp;rf+1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[1] =<br />
                                                                            ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1613:76: warning: ‘rf’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[0] = rf[0];<br />
                                                                            ^<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbBlend_a64_mask.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCdef.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCdefProcess.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCodingLoop.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCodingUnit.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbDeblockingFilter.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
      <tr>
        <td>:warning:</td>
        <td>
        Danger found 1 violations with this PR. Due to GitHub's max issue comment size, the number shown has been truncated to 0.
        </td>
      </tr>
  </tbody>
</table>

### Tests: 

Name | Value_param | Status | Time | Classname|
--- | --- | --- | --- | ---|
CheckEncOptionsUsingBitstream/RcTest6 | RcTest6: RateControlMode=1, TargetBitRate=500000,  | run | 8.429 | SvtAv1/CodingOptionTest|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request closed without merging**
