### PR TITLE
distribute unit tests in GitHub CI

### PR DESCRIPTION
**Pull request by edmond-zhu**
1. add a quick test with GTest sharded mode to accelerate: parallel running unit tests in multiple tasks.

PS： this PR is only a verification test for real PR

### CODE REVIEW

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest-all.cc.o<br />
[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest_main.cc.o<br />
[ 59%] Linking CXX shared library ../../../../../Bin/Release/libgtest_all.so<br />
[ 59%] Built target gtest_all<br />
Scanning dependencies of target SvtAv1UnitTests<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘update_mi_map’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1614:76: warning: ‘*((void *)&amp;rf+1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[1] =<br />
                                                                            ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1613:76: warning: ‘rf’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[0] = rf[0];<br />
                                                                            ^<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbBlend_a64_mask.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCdef.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCdefProcess.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCodingLoop.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCodingUnit.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbDeblockingFilter.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest-all.cc.o<br />
[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest_main.cc.o<br />
[ 59%] Linking CXX shared library ../../../../../Bin/Release/libgtest_all.so<br />
[ 59%] Built target gtest_all<br />
Scanning dependencies of target SvtAv1UnitTests<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘update_mi_map’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1614:76: warning: ‘*((void *)&amp;rf+1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[1] =<br />
                                                                            ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1613:76: warning: ‘rf’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[0] = rf[0];<br />
                                                                            ^<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbBlend_a64_mask.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCdef.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCdefProcess.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCodingLoop.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCodingUnit.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbDeblockingFilter.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest-all.cc.o<br />
[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest_main.cc.o<br />
[ 59%] Linking CXX shared library ../../../../../Bin/Release/libgtest_all.so<br />
[ 59%] Built target gtest_all<br />
Scanning dependencies of target SvtAv1UnitTests<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘update_mi_map’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1614:76: warning: ‘*((void *)&amp;rf+1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[1] =<br />
                                                                            ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1613:76: warning: ‘rf’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[0] = rf[0];<br />
                                                                            ^<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbBlend_a64_mask.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCdef.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCdefProcess.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCodingLoop.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCodingUnit.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbDeblockingFilter.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest-all.cc.o<br />
[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest_main.cc.o<br />
[ 59%] Linking CXX shared library ../../../../../Bin/Release/libgtest_all.so<br />
[ 59%] Built target gtest_all<br />
Scanning dependencies of target SvtAv1UnitTests<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘update_mi_map’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1614:76: warning: ‘*((void *)&amp;rf+1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[1] =<br />
                                                                            ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1613:76: warning: ‘rf’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[0] = rf[0];<br />
                                                                            ^<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbBlend_a64_mask.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCdef.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCdefProcess.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCodingLoop.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCodingUnit.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbDeblockingFilter.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest-all.cc.o<br />
[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest_main.cc.o<br />
[ 59%] Linking CXX shared library ../../../../../Bin/Release/libgtest_all.so<br />
[ 59%] Built target gtest_all<br />
Scanning dependencies of target SvtAv1UnitTests<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘update_mi_map’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1614:76: warning: ‘*((void *)&amp;rf+1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[1] =<br />
                                                                            ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1613:76: warning: ‘rf’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[0] = rf[0];<br />
                                                                            ^<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbBlend_a64_mask.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCdef.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCdefProcess.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCodingLoop.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCodingUnit.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbDeblockingFilter.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest-all.cc.o<br />
[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest_main.cc.o<br />
[ 59%] Linking CXX shared library ../../../../../Bin/Release/libgtest_all.so<br />
[ 59%] Built target gtest_all<br />
Scanning dependencies of target SvtAv1UnitTests<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘update_mi_map’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1614:76: warning: ‘*((void *)&amp;rf+1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[1] =<br />
                                                                            ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1613:76: warning: ‘rf’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[0] = rf[0];<br />
                                                                            ^<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbBlend_a64_mask.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCdef.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCdefProcess.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCodingLoop.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCodingUnit.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbDeblockingFilter.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest-all.cc.o<br />
[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest_main.cc.o<br />
[ 59%] Linking CXX shared library ../../../../../Bin/Release/libgtest_all.so<br />
[ 59%] Built target gtest_all<br />
Scanning dependencies of target SvtAv1UnitTests<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘update_mi_map’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1614:76: warning: ‘*((void *)&amp;rf+1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[1] =<br />
                                                                            ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1613:76: warning: ‘rf’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[0] = rf[0];<br />
                                                                            ^<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbBlend_a64_mask.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCdef.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCdefProcess.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCodingLoop.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCodingUnit.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbDeblockingFilter.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Cidana-Developers** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest-all.cc.o<br />
[ 59%] Building CXX object third_party/googletest/CMakeFiles/gtest_all.dir/src/gtest_main.cc.o<br />
[ 59%] Linking CXX shared library ../../../../../Bin/Release/libgtest_all.so<br />
[ 59%] Built target gtest_all<br />
Scanning dependencies of target SvtAv1UnitTests<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c.o<br />
[ 59%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c.o<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘update_mi_map’:<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1615:76: warning: ‘*((void *)&amp;rf+1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[1] =<br />
                                                                            ^<br />
/home/jenkins/workspace/Open-SVTAV1-Linux-GCC-Build/Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c:1614:76: warning: ‘rf’ may be used uninitialized in this function [-Wmaybe-uninitialized]<br />
                 mi_ptr[mi_x + mi_y * mi_stride].mbmi.block_mi.ref_frame[0] = rf[0];<br />
                                                                            ^<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCdef.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCdefProcess.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbCodingLoop.c.o<br />
[ 60%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbCodingUnit.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/<strong>/Source/Lib/Encoder/Codec/EbDeblockingFilter.c.o<br />
[ 61%] Building C object test/CMakeFiles/SvtAv1UnitTests.dir/</strong>/Source/Lib/Encoder/Codec/EbDlfProcess.c.o</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by edmond-zhu** [comment]
merged, close it

**Pull request closed without merging**
